const { kv } = require('@vercel/kv');

const DEFAULT_PRODUCTS = [
  { id:1, name:'Sérum Nebula', desc:'Activador celular cuántico', category:'serums', price:189, old:269, imgs:['productos/creap.jpg'], rating:4.9, reviews:2841, badge:'stock', badgeText:'Últimas 8', peso:'30 ml', modo_uso:'Aplicar 2-3 gotas sobre el rostro limpio. Masajear suavemente en movimientos circulares ascendentes. Usar mañana y noche.', ingredientes:'Aqua, Niacinamide 10%, Hyaluronic Acid, Retinol 0.1%, Vitamin C, Peptide Complex, Aloe Vera Extract, Glycerin.', beneficios:['Reduce arrugas en 72h','Hidratación profunda 24h','Ilumina el tono de piel','Estimula el colágeno'], para_quien:'Todo tipo de piel. Especialmente recomendado para piel madura o con signos de envejecimiento.' },
  { id:2, name:'Palette Aurora', desc:'18 tonos holográficos', category:'maquillaje', price:134, old:189, imgs:['productos/cara.jpg'], rating:4.8, reviews:1932, badge:'new', badgeText:'Nuevo', peso:'18 x 1.5g', modo_uso:'Aplicar con pincel o dedos sobre párpados limpios y preparados con base. Para mayor intensidad, aplicar húmedo.', ingredientes:'Mica, Talc, Zinc Stearate, Dimethicone, Silica, Carmine, Titanium Dioxide, Iron Oxides.', beneficios:['18 tonos únicos','Alta pigmentación','Duración 12 horas','Finish holográfico'], para_quien:'Apta para todo tipo de piel. Dermatológicamente testeada.' },
  { id:3, name:'Cosmos Noir Cream', desc:'Regeneración nocturna profunda', category:'cremas', price:159, old:229, imgs:['productos/dior.jpg'], rating:4.9, reviews:3102, badge:'stock', badgeText:'Últimas 12', peso:'50 ml', modo_uso:'Aplicar cada noche sobre rostro y cuello con movimientos suaves. Dejar actuar durante 8 horas mientras duermes.', ingredientes:'Aqua, Shea Butter, Retinol Complex, Peptide Matrix, Hyaluronic Acid, Ceramides, Vitamin E, Jojoba Oil.', beneficios:['Regeneración celular nocturna','Reduce manchas oscuras','Textura sedosa','Efecto antienvejecimiento'], para_quien:'Piel seca, mixta o madura. No recomendado para piel muy grasa.' },
  { id:4, name:'Labial Plasma', desc:'Pigmento de larga duración 24h', category:'labiales', price:74, old:99, imgs:['productos/versace.jpg'], rating:4.7, reviews:4218, badge:'', badgeText:'', peso:'3.5g', modo_uso:'Aplicar directamente sobre labios. Para mayor precisión usar el borde del labial. No requiere delineador.', ingredientes:'Ricinus Communis Oil, Cera Alba, Carnauba Wax, Vitamin E, Hyaluronic Acid, Pigments.', beneficios:['Duración 24 horas','No se corre','Hidrata los labios','Color ultra intenso'], para_quien:'Apto para todo tipo de labios. No testado en animales.' },
  { id:5, name:'Eye Matrix', desc:'Contorno de ojos biofotónico', category:'ojos', price:119, old:169, imgs:['productos/creap.jpg'], rating:4.8, reviews:1567, badge:'new', badgeText:'Nuevo', peso:'15 ml', modo_uso:'Aplicar con el aplicador en el contorno del ojo. Dar pequeños toquecitos hasta absorción. Usar mañana y noche.', ingredientes:'Aqua, Caffeine 5%, Peptide Eye Complex, Hyaluronic Acid, Vitamin K, Aloe Vera, Cucumber Extract.', beneficios:['Elimina ojeras en 7 días','Reduce bolsas','Efecto tensor inmediato','Hidratación intensa'], para_quien:'Todo tipo de piel. Especialmente para piel con ojeras o signos de cansancio.' },
  { id:6, name:'Solar Shield SPF 60', desc:'Protección UV inteligente', category:'proteccion', price:89, old:129, imgs:['productos/creap.jpg'], rating:4.9, reviews:2290, badge:'stock', badgeText:'Casi agotado', peso:'50 ml', modo_uso:'Aplicar 15 minutos antes de exposición solar. Reaplicar cada 2 horas. Usar como último paso de tu rutina.', ingredientes:'Zinc Oxide, Titanium Dioxide, Hyaluronic Acid, Vitamin C, Niacinamide, Aloe Vera, Aqua.', beneficios:['Protección UVA/UVB','SPF 60 PA++++','No deja residuo blanco','Hidrata mientras protege'], para_quien:'Todo tipo de piel. Indispensable uso diario.' },
  { id:7, name:'Glow Essence', desc:'Esencia iluminadora celestial', category:'serums', price:145, old:199, imgs:['productos/creap.jpg'], rating:4.8, reviews:987, badge:'new', badgeText:'Nuevo', peso:'30 ml', modo_uso:'Aplicar 3-4 gotas sobre rostro limpio antes de la crema hidratante. Usar preferentemente en la noche.', ingredientes:'Aqua, Vitamin C 15%, Alpha Arbutin, Ferulic Acid, Niacinamide, Rose Hip Oil, Squalane.', beneficios:['Ilumina al instante','Unifica el tono','Antioxidante potente','Reduce hiperpigmentación'], para_quien:'Piel con manchas, opaca o con tono irregular.' },
  { id:8, name:'Velvet Foundation', desc:'Base de cobertura total aterciopelada', category:'maquillaje', price:112, old:159, imgs:['productos/cara.jpg'], rating:4.7, reviews:2103, badge:'', badgeText:'', peso:'30 ml', modo_uso:'Aplicar con brocha, esponja o dedos. Difuminar desde el centro hacia afuera. Fijar con polvo translúcido.', ingredientes:'Aqua, Cyclopentasiloxane, Dimethicone, Titanium Dioxide, Iron Oxides, Glycerin, Vitamin E.', beneficios:['Cobertura total buildable','Duración 16 horas','Finish aterciopelado','30 tonos disponibles'], para_quien:'Todo tipo de piel. Especialmente piel con imperfecciones.' },
  { id:9, name:'Midnight Repair', desc:'Mascarilla nocturna de lujo', category:'cremas', price:175, old:249, imgs:['productos/dior.jpg'], rating:4.9, reviews:1456, badge:'stock', badgeText:'Últimas 5', peso:'75 ml', modo_uso:'Aplicar generosamente como último paso de tu rutina nocturna. No enjuagar. Dejar actuar toda la noche.', ingredientes:'Shea Butter, Squalane, Bakuchiol, Peptide Complex, Ceramides, Hyaluronic Acid, Rose Extract.', beneficios:['Reparación intensiva overnight','Piel como nueva al despertar','Ultra nutritiva','Efecto plumping'], para_quien:'Piel seca, deshidratada o muy sensible.' },
  { id:10, name:'Lip Gloss Pulsar', desc:'Gloss voluminizador con efecto plumping', category:'labiales', price:59, old:85, imgs:['productos/versace.jpg'], rating:4.6, reviews:3421, badge:'new', badgeText:'Nuevo', peso:'5 ml', modo_uso:'Aplicar sobre labios desnudos o sobre labial. Para mayor volumen aplicar en el centro del labio superior.', ingredientes:'Ricinus Communis Oil, Polybutene, Peppermint Oil, Vitamin E, Hyaluronic Acid, Collagen Peptides.', beneficios:['Volumen inmediato','Efecto plumping visible','Brillo ultra reflectante','Hidratación intensa'], para_quien:'Para quien desea labios más voluminosos y jugosos.' },
  { id:11, name:'Mascara Cosmos', desc:'Máscara de pestañas volumizadora 4D', category:'ojos', price:79, old:110, imgs:['productos/cara.jpg'], rating:4.8, reviews:5234, badge:'', badgeText:'', peso:'10 ml', modo_uso:'Aplicar en zigzag desde la raíz hasta las puntas. Para mayor volumen aplicar una segunda capa antes de que seque.', ingredientes:'Aqua, Beeswax, Carnauba Wax, Iron Oxides, Panthenol, Biotin, Vitamin B5.', beneficios:['Volumen 4D extremo','No mancha','Resistente al agua','Alarga y riza'], para_quien:'Todo tipo de pestañas. Especialmente finas o cortas.' },
  { id:12, name:'Hydra Boost Cream', desc:'Crema hidratante de ácido hialurónico puro', category:'cremas', price:129, old:179, imgs:['productos/dior.jpg'], rating:4.9, reviews:2876, badge:'', badgeText:'', peso:'50 ml', modo_uso:'Aplicar sobre rostro limpio mañana y noche. Ideal como base antes del maquillaje. Masajear hasta completa absorción.', ingredientes:'Aqua, Hyaluronic Acid 2%, Glycerin, Ceramides, Aloe Vera, Panthenol, Niacinamide, Vitamin B5.', beneficios:['Hidratación 72 horas','Rellena líneas de expresión','Textura ultraligera','Apta para piel sensible'], para_quien:'Todo tipo de piel. Especialmente piel deshidratada.' },
  { id:13, name:'Retinol Night Force', desc:'Tratamiento intensivo antiedad con retinol puro', category:'serums', price:215, old:299, imgs:['productos/creap.jpg'], rating:4.9, reviews:1123, badge:'stock', badgeText:'Premium', peso:'30 ml', modo_uso:'Usar solo por las noches. Aplicar 2-3 gotas sobre rostro limpio y seco. Comenzar 2 veces por semana e ir aumentando.', ingredientes:'Aqua, Retinol 0.5%, Peptide Matrix, Hyaluronic Acid, Vitamin E, Squalane, Niacinamide.', beneficios:['Anti-aging clínico','Reduce arrugas profundas','Regenera la piel','Resultados en 4 semanas'], para_quien:'Piel madura. No recomendado para embarazadas. Usar protector solar obligatoriamente.' },
  { id:14, name:'Contouring Pro', desc:'Kit de contorno y iluminación profesional', category:'maquillaje', price:98, old:139, imgs:['productos/cara.jpg'], rating:4.7, reviews:1876, badge:'new', badgeText:'Nuevo', peso:'2 x 8g', modo_uso:'Aplicar el tono oscuro en las zonas a contornear con pincel angular. El iluminador en los puntos altos del rostro.', ingredientes:'Mica, Talc, Silica, Zinc Stearate, Dimethicone, Vitamin E, Iron Oxides, Titanium Dioxide.', beneficios:['Contorno profesional','Iluminador intenso','Larga duración','Blendable fácil'], para_quien:'Todo tipo de piel y tono.' },
  { id:15, name:'Rose Petal Toner', desc:'Tónico equilibrante de rosas de Damasco', category:'serums', price:69, old:95, imgs:['productos/creap.jpg'], rating:4.6, reviews:2341, badge:'', badgeText:'', peso:'150 ml', modo_uso:'Aplicar sobre algodón o directamente con las manos tras la limpieza. Dar toquecitos suaves hasta absorción.', ingredientes:'Rosa Damascena Water, Glycerin, Niacinamide, Aloe Vera, Witch Hazel, Centella Asiatica, Hyaluronic Acid.', beneficios:['Equilibra el pH de la piel','Minimiza poros','Refresca e hidrata','Aroma floral natural'], para_quien:'Todo tipo de piel. Especialmente piel mixta o con poros dilatados.' },
  { id:16, name:'Lip Liner Stellar', desc:'Delineador de labios de larga duración', category:'labiales', price:45, old:65, imgs:['productos/versace.jpg'], rating:4.7, reviews:1987, badge:'', badgeText:'', peso:'1.2g', modo_uso:'Delinear el contorno natural del labio. Se puede usar para rellenar el labio completo como base de labial.', ingredientes:'Cera Alba, Carnauba Wax, Ricinus Communis Oil, Vitamin E, Iron Oxides, Titanium Dioxide.', beneficios:['Precisión máxima','No se corre','Duración 12 horas','Define y agranda labios'], para_quien:'Para un maquillaje de labios preciso y duradero.' },
  { id:17, name:'Eye Shadow Stellar', desc:'Sombra individual de alta pigmentación', category:'ojos', price:55, old:79, imgs:['productos/cara.jpg'], rating:4.8, reviews:3102, badge:'', badgeText:'', peso:'2g', modo_uso:'Aplicar con pincel o dedo sobre párpado. Para look ahumado difuminar los bordes con pincel difuminador.', ingredientes:'Mica, Talc, Zinc Stearate, Silica, Dimethicone, Carmine, Ultramarines, Iron Oxides.', beneficios:['Pigmentación extrema','Brillo metálico intenso','Duración 10 horas','40 tonos disponibles'], para_quien:'Todo tipo de piel. Dermatológicamente testeada y oftalmológicamente aprobada.' },
  { id:18, name:'UV Defense Mist', desc:'Bruma protectora SPF 50 para retocar', category:'proteccion', price:75, old:105, imgs:['productos/creap.jpg'], rating:4.7, reviews:1234, badge:'new', badgeText:'Nuevo', peso:'100 ml', modo_uso:'Agitar bien. Rociar a 20cm del rostro con ojos cerrados. Usar cada 2 horas como retoque sobre maquillaje.', ingredientes:'Aqua, Ethylhexyl Methoxycinnamate, Zinc Oxide, Glycerin, Hyaluronic Acid, Aloe Vera, Vitamin C.', beneficios:['Retoca sin arruinar el maquillaje','SPF 50 PA+++','Fija el maquillaje','Efecto refrescante'], para_quien:'Para quienes necesitan protección durante el día sin retirar el maquillaje.' },
  { id:19, name:'Elixir Noir Perfume', desc:'Eau de Parfum edición limitada', category:'premium', price:289, old:389, imgs:['productos/versace.jpg'], rating:5.0, reviews:456, badge:'stock', badgeText:'Ed. Limitada', peso:'50 ml', modo_uso:'Aplicar en puntos de calor: muñecas, cuello, detrás de las orejas. No frotar para preservar las notas.', ingredientes:'Alcohol Denat., Aqua, Parfum, Rosa Damascena, Jasmine, Oud Wood, Vanilla, Musk, Bergamot.', beneficios:['Duración 8-12 horas','Estela intensa','Notas únicas de Oud','Edición limitada coleccionable'], para_quien:'Para quien busca una fragancia sofisticada y memorable.' },
  { id:20, name:'Gold Collagen Mask', desc:'Mascarilla de colágeno y partículas de oro 24k', category:'premium', price:245, old:345, imgs:['productos/dior.jpg'], rating:4.9, reviews:789, badge:'stock', badgeText:'Premium', peso:'5 x 25ml', modo_uso:'Limpiar el rostro. Aplicar la mascarilla 20-30 minutos. Retirar y masajear el exceso hasta absorción. 2 veces por semana.', ingredientes:'Collagen, Gold 24K, Hyaluronic Acid, Peptide Complex, Vitamin C, Rose Extract, Aloe Vera.', beneficios:['Efecto lifting inmediato','Iluminación extrema','Anti-aging intensivo','Textura lámina dorada'], para_quien:'Para ocasiones especiales o tratamiento intensivo antiedad.' }
];

module.exports = async function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  if (req.method === 'OPTIONS') return res.status(200).end();

  if (req.method === 'GET') {
    if (req.query.resenas === '1') {
      const resenas = (await kv.get('lumiere_resenas') || []).filter(r => r.aprobada);
      return res.status(200).json(resenas);
    }
    const productos = await kv.get('lumiere_productos');
    return res.status(200).json(productos && productos.length > 0 ? productos : DEFAULT_PRODUCTS);
  }

  if (req.method === 'POST') {
    const { productoId, nombre, estrellas, comentario } = req.body;
    if (!nombre || !comentario || !estrellas) return res.status(400).json({ error: 'Completa todos los campos' });
    if (estrellas < 1 || estrellas > 5) return res.status(400).json({ error: 'Estrellas inválidas' });
    const resenas = await kv.get('lumiere_resenas') || [];
    resenas.unshift({ id: Date.now(), productoId, nombre: nombre.trim(), estrellas: Number(estrellas), comentario: comentario.trim(), fecha: new Date().toISOString(), aprobada: false });
    await kv.set('lumiere_resenas', resenas);
    return res.status(200).json({ ok: true, msg: 'Reseña enviada. Aparecerá tras ser aprobada.' });
  }

  return res.status(405).json({ error: 'Método no permitido' });
};
